#!/usr/bin/env node
/**
 * Sync data/photoLogCsv.csv, printOfferings.csv, and storeConfig.csv
 * into src/data/gallery.ts and src/data/products.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const dataDir = join(root, "data");

function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = "";
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    const next = text[i + 1];

    if (inQuotes) {
      if (char === '"' && next === '"') {
        field += '"';
        i++;
      } else if (char === '"') {
        inQuotes = false;
      } else {
        field += char;
      }
      continue;
    }

    if (char === '"') {
      inQuotes = true;
    } else if (char === ",") {
      row.push(field);
      field = "";
    } else if (char === "\n" || (char === "\r" && next === "\n")) {
      row.push(field);
      field = "";
      if (row.some((cell) => cell.trim() !== "") || rows.length === 0) {
        rows.push(row);
      }
      row = [];
      if (char === "\r") i++;
    } else if (char !== "\r") {
      field += char;
    }
  }

  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }

  return rows;
}

function rowsToObjects(rows) {
  const [header, ...dataRows] = rows;
  const keys = header.map((key) => key.trim());
  return dataRows.map((cells) => {
    const obj = {};
    keys.forEach((key, index) => {
      obj[key] = (cells[index] ?? "").trim();
    });
    return obj;
  });
}

function loadCsv(filename) {
  const text = readFileSync(join(dataDir, filename), "utf8");
  return rowsToObjects(parseCsv(text));
}

function isYes(value) {
  return String(value ?? "")
    .trim()
    .toLowerCase() === "y";
}

function filenameToSlug(filename) {
  return filename
    .replace(/\.(jpe?g|png|webp)$/i, "")
    .trim()
    .replace(/\s+/g, "")
    .toLowerCase();
}

function parseCategory(raw) {
  const tags = raw
    .split(",")
    .map((tag) => tag.trim().toLowerCase())
    .filter(Boolean);

  if (tags.length === 0) return "landscape";

  if (tags[0] === "nature" && tags[1]) {
    return tags[1] === "wildlife" ? "wildlife" : "landscape";
  }

  return tags[0] === "wildlife" ? "wildlife" : "landscape";
}

function imageSrcFor(filename, category) {
  const folder = category === "wildlife" ? "wildlife" : "landscapes";
  const slug = filenameToSlug(filename);
  return `/gallery/${folder}/${slug}.jpg`;
}

function escapeString(value) {
  return String(value)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n");
}

function formatStringArray(values) {
  if (!values || values.length === 0) return undefined;
  return `[${values.map((v) => `"${escapeString(v)}"`).join(", ")}]`;
}

function rowField(row, ...keys) {
  for (const key of keys) {
    if (row[key] != null && String(row[key]).trim() !== "") {
      return String(row[key]).trim();
    }
  }
  return "";
}

function generateGalleryTs(items) {
  const itemBlocks = items.map((item, index) => {
    const lines = [
      `    id: "${index + 1}",`,
      `    title: "${escapeString(item.title)}",`,
      `    slug: "${item.slug}",`,
      `    category: "${item.category}",`,
    ];

    if (item.location) lines.push(`    location: "${escapeString(item.location)}",`);
    if (item.caption) lines.push(`    caption: "${escapeString(item.caption)}",`);
    if (item.altText) lines.push(`    altText: "${escapeString(item.altText)}",`);
    if (item.keywords?.length) {
      lines.push(`    keywords: ${formatStringArray(item.keywords)},`);
    }
    lines.push(`    imageSrc: "${item.imageSrc}",`);
    lines.push(`    featured: ${item.featured},`);
    lines.push(`    inGallery: ${item.inGallery},`);
    lines.push(`    inStore: ${item.inStore},`);
    if (item.dateTaken) lines.push(`    dateTaken: "${escapeString(item.dateTaken)}",`);
    if (item.sku) lines.push(`    sku: "${escapeString(item.sku)}",`);
    if (item.printNote) lines.push(`    printNote: "${escapeString(item.printNote)}",`);

    return `  {\n${lines.join("\n")}\n  }`;
  });

  return `// @generated by scripts/sync-data.mjs — do not edit by hand
export type GalleryCategory = "wildlife" | "landscape";

export type GalleryItem = {
  id: string;
  title: string;
  slug: string;
  category: GalleryCategory;
  location?: string;
  caption?: string;
  altText?: string;
  keywords?: string[];
  imageSrc: string;
  featured: boolean;
  inGallery: boolean;
  inStore: boolean;
  dateTaken?: string;
  sku?: string;
  printNote?: string;
};

export const HOMEPAGE_PREVIEW_LIMIT = 4;

export const galleryItems: GalleryItem[] = [
${itemBlocks.join(",\n")}
];

export function getByCategory(category: GalleryCategory): GalleryItem[] {
  return galleryItems.filter((item) => item.category === category);
}

export function getGalleryItems(): GalleryItem[] {
  return galleryItems.filter((item) => item.inGallery);
}

export function getStoreItems(): GalleryItem[] {
  return galleryItems.filter((item) => item.inStore);
}

export function getHomepagePreviews(): {
  gallery: GalleryItem[];
  store: GalleryItem[];
} {
  const usedSlugs = new Set<string>();

  const store = galleryItems
    .filter((item) => item.featured && item.inStore)
    .slice(0, HOMEPAGE_PREVIEW_LIMIT);
  store.forEach((item) => usedSlugs.add(item.slug));

  const gallery = galleryItems
    .filter((item) => item.featured && item.inGallery && !usedSlugs.has(item.slug))
    .slice(0, HOMEPAGE_PREVIEW_LIMIT);

  return { gallery, store };
}

export function getFeaturedGallery(): GalleryItem[] {
  return galleryItems.filter((item) => item.featured && item.inGallery);
}

export function getFeaturedStore(): GalleryItem[] {
  return galleryItems.filter((item) => item.featured && item.inStore);
}

/** @deprecated Use getFeaturedGallery or getFeaturedStore */
export function getFeatured(): GalleryItem[] {
  return galleryItems.filter((item) => item.featured);
}

/** @deprecated Use getStoreItems */
export function getPrints(): GalleryItem[] {
  return getStoreItems();
}

export function getBySlug(slug: string): GalleryItem | undefined {
  return galleryItems.find((item) => item.slug === slug);
}

/** @deprecated Use galleryItems */
export const featuredGallery = galleryItems;
`;
}

function generateProductsTs(offerings, storeConfig, galleryItems) {
  const offeringBlocks = offerings.map(
    (offering) => `  {
    id: "${escapeString(offering.id)}",
    slug: "${escapeString(offering.slug)}",
    label: "${escapeString(offering.label)}",
    description: "${escapeString(offering.description)}",
    medium: "${escapeString(offering.medium)}",
    stripeProductId: "${escapeString(offering.stripeProductId)}",
    active: ${offering.active},
  }`,
  );

  const offeringSlugs = new Set(offerings.filter((o) => o.active).map((o) => o.slug));
  for (const item of galleryItems.filter((entry) => entry.inStore)) {
    if (!offeringSlugs.has(item.slug)) {
      console.warn(`Warning: store item "${item.slug}" has no active print offerings`);
    }
  }

  for (const offering of offerings) {
    const photo = galleryItems.find((item) => item.slug === offering.slug);
    if (!photo) {
      console.warn(
        `Warning: offering "${offering.label}" references unknown photo slug "${offering.slug}"`,
      );
    }
  }

  return `// @generated by scripts/sync-data.mjs — do not edit by hand
import { galleryItems, type GalleryItem } from "./gallery";

export type PrintOffering = {
  id: string;
  slug: string;
  label: string;
  description: string;
  medium: "print" | "canvas";
  stripeProductId: string;
  active: boolean;
};

export type StoreConfig = {
  stripeShippingProductId: string;
  checkoutEnabled: boolean;
  shipsTo: string;
  turnaroundDays: string;
};

export const printOfferings: PrintOffering[] = [
${offeringBlocks.join(",\n")}
];

export const storeConfig: StoreConfig = {
  stripeShippingProductId: "${escapeString(storeConfig.stripeShippingProductId)}",
  checkoutEnabled: ${storeConfig.checkoutEnabled},
  shipsTo: "${escapeString(storeConfig.shipsTo)}",
  turnaroundDays: "${escapeString(storeConfig.turnaroundDays)}",
};

export function getActiveOfferings(): PrintOffering[] {
  return printOfferings.filter((offering) => offering.active);
}

export function getOfferingsForSlug(slug: string): PrintOffering[] {
  const item = galleryItems.find((entry) => entry.slug === slug);
  if (!item || !item.inStore) return [];

  return getActiveOfferings().filter((offering) => offering.slug === slug);
}

export function getStoreItemForSlug(slug: string): GalleryItem | undefined {
  return galleryItems.find((item) => item.slug === slug && item.inStore);
}
`;
}

function main() {
  const photoRows = loadCsv("photoLogCsv.csv");
  const offeringRows = loadCsv("printOfferings.csv");
  const configRows = loadCsv("storeConfig.csv");

  const storeConfigMap = Object.fromEntries(
    configRows.map((row) => [row.key, row.value]),
  );

  const storeConfig = {
    stripeShippingProductId: storeConfigMap.stripe_shipping_product_id ?? "",
    checkoutEnabled: isYes(storeConfigMap.checkout_enabled ?? "n"),
    shipsTo: storeConfigMap.ships_to ?? "US",
    turnaroundDays: storeConfigMap.turnaround_days ?? "7-14",
  };

  const galleryItems = photoRows.map((row) => {
    const filename = row.filename;
    const slug = filenameToSlug(filename);
    const category = parseCategory(row.categroy ?? "");

    return {
      title: row.title,
      slug,
      category,
      location: row.location || undefined,
      caption: row.caption || undefined,
      altText: row.alt_text || undefined,
      keywords: row.keywords
        ? row.keywords
            .split(",")
            .map((keyword) => keyword.trim())
            .filter(Boolean)
        : undefined,
      imageSrc: imageSrcFor(filename, category),
      featured: isYes(row["featured "] ?? row.featured ?? "n"),
      inGallery: isYes(row.gallery ?? "n"),
      inStore: isYes(row.store ?? "n"),
      dateTaken: row.date_taken || undefined,
      sku: row.sku || undefined,
      printNote: row.print_note || undefined,
    };
  });

  const offerings = offeringRows.map((row, index) => {
    const filename = rowField(row, "filename");
    const slug = filenameToSlug(filename);
    const stripeProductId = rowField(row, "id", "stripe_product_id");
    const label = rowField(row, "Label", "label");
    const description = rowField(row, "description");
    const mediumRaw = rowField(row, "medium").toLowerCase();
    const medium =
      mediumRaw === "canvas" || mediumRaw === "print"
        ? mediumRaw
        : /canvas/i.test(label)
          ? "canvas"
          : "print";

    if (!slug || !stripeProductId || !label) {
      console.error(`Error: printOfferings.csv row ${index + 2} is missing filename, Label, or id`);
      process.exit(1);
    }

    return {
      id: stripeProductId,
      slug,
      label,
      description,
      medium,
      stripeProductId,
      active: isYes(row.active ?? "y"),
    };
  });

  const galleryTs = generateGalleryTs(galleryItems);
  const productsTs = generateProductsTs(offerings, storeConfig, galleryItems);

  writeFileSync(join(root, "src/data/gallery.ts"), galleryTs);
  writeFileSync(join(root, "src/data/products.ts"), productsTs);

  console.log(
    `Synced ${galleryItems.length} gallery items and ${offerings.length} print offerings.`,
  );
}

main();
