// @generated by scripts/sync-data.mjs — do not edit by hand
export type GalleryCategory = "wildlife" | "landscape";

export type GalleryItem = {
  id: string;
  title: string;
  slug: string;
  category: GalleryCategory;
  location?: string;
  caption?: string;
  altText?: string;
  keywords?: string[];
  imageSrc: string;
  featured: boolean;
  inGallery: boolean;
  inStore: boolean;
  dateTaken?: string;
  sku?: string;
  printNote?: string;
};

export const HOMEPAGE_PREVIEW_LIMIT = 4;

export const galleryItems: GalleryItem[] = [
  {
    id: "1",
    title: "New York 8 Pointer",
    slug: "8-point-buck-upstate-ny",
    category: "wildlife",
    location: "Upstate NY",
    altText: "White-tailed buck with an 8-point rack staring downrange in Upstate NY",
    imageSrc: "/gallery/wildlife/8-point-buck-upstate-ny.jpg",
    featured: true,
    inGallery: true,
    inStore: true,
  },
  {
    id: "2",
    title: "Barred Owl",
    slug: "barred-owl-wachusett-reservation",
    category: "wildlife",
    location: "Princeton MA",
    altText: "A barred owl perched on a broken tree at Wachusett Mountain Reservation in Princeton",
    imageSrc: "/gallery/wildlife/barred-owl-wachusett-reservation.jpg",
    featured: true,
    inGallery: true,
    inStore: false,
  },
  {
    id: "3",
    title: "Bondcliff Ridge",
    slug: "bondcliff-sunset-white-mountains-pemi-loop",
    category: "landscape",
    location: "Pemigewasset Wilderness",
    altText: "Bondcliff Trail and cliffs during golden hour in the Pemigewasset Wilderness",
    imageSrc: "/gallery/landscapes/bondcliff-sunset-white-mountains-pemi-loop.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "4",
    title: "Plumage",
    slug: "common-loon-wing-spread-massachusetts",
    category: "wildlife",
    location: "Ashburnham MA",
    altText: "Common loon spreading its wings",
    imageSrc: "/gallery/wildlife/common-loon-wing-spread-massachusetts.jpg",
    featured: true,
    inGallery: true,
    inStore: false,
  },
  {
    id: "5",
    title: "11/19/25 - Auora Borealis, MA",
    slug: "cowee-pond-northern-lights-massachusetts",
    category: "landscape",
    location: "Gardner MA",
    altText: "Northern Lights over Cowee Pond in Gardner",
    imageSrc: "/gallery/landscapes/cowee-pond-northern-lights-massachusetts.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "6",
    title: "Drab Foliage - Fall 2025",
    slug: "drought-foliage-white-mountain-forest",
    category: "landscape",
    location: "Woodstock NH",
    altText: "Drab foliage in Kinsman Notch during the dry fall of 2025",
    imageSrc: "/gallery/landscapes/drought-foliage-white-mountain-forest.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "7",
    title: "Trees and Leaves",
    slug: "fall-foliage-hancock-trail-nh",
    category: "landscape",
    location: "Lincoln NH",
    altText: "White Mountain hiking trail during peak fall foliage in New Hampshire",
    imageSrc: "/gallery/landscapes/fall-foliage-hancock-trail-nh.jpg",
    featured: true,
    inGallery: true,
    inStore: true,
  },
  {
    id: "8",
    title: "Frog on Pad",
    slug: "frog-sitting-on-lillypad-wachusett-meadow",
    category: "wildlife",
    location: "Princeton MA",
    altText: "Frog sitting on a lily pad at Wachusett Meadow Wildlife Sanctuary in Princeton",
    imageSrc: "/gallery/wildlife/frog-sitting-on-lillypad-wachusett-meadow.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "9",
    title: "Hummingbird in Flight",
    slug: "hummingbird-flying-ashburnham-ma",
    category: "wildlife",
    location: "Ashburnham MA",
    altText: "Hummingbird in flight with wings flapping",
    imageSrc: "/gallery/wildlife/hummingbird-flying-ashburnham-ma.jpg",
    featured: true,
    inGallery: true,
    inStore: false,
  },
  {
    id: "10",
    title: "Sunrise in the Notch",
    slug: "kinsman-notch-sunrise-woodstock-nh",
    category: "landscape",
    location: "Kinsman Notch",
    altText: "The sun rises over the mountains",
    imageSrc: "/gallery/landscapes/kinsman-notch-sunrise-woodstock-nh.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "11",
    title: "Calm River",
    slug: "millers-river-sunrise-massachusetts",
    category: "landscape",
    location: "Lake Dennison",
    altText: "A calm morning by the Millers River",
    imageSrc: "/gallery/landscapes/millers-river-sunrise-massachusetts.jpg",
    featured: true,
    inGallery: true,
    inStore: true,
  },
  {
    id: "12",
    title: "Tiny Saw Whet",
    slug: "northern-saw-whet-owl-portrait",
    category: "wildlife",
    location: "Winchendon MA",
    altText: "A tiny northern saw-whet owl perched on a pine during a windstorm",
    imageSrc: "/gallery/wildlife/northern-saw-whet-owl-portrait.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "13",
    title: "Otter Candid",
    slug: "river-otter-fishing-ma",
    category: "wildlife",
    location: "Royalston MA",
    altText: "A river otter at Eagle Preserve in Royalston",
    imageSrc: "/gallery/wildlife/river-otter-fishing-ma.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "14",
    title: "Golden Sunrise",
    slug: "sunrise-fitchburg-central-ma",
    category: "landscape",
    location: "Fitchburg MA",
    altText: "A glowing yellow sunrise over a lake in Fitchburg",
    imageSrc: "/gallery/landscapes/sunrise-fitchburg-central-ma.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "15",
    title: "Misty Morning",
    slug: "sunrise-wachusett-meadow-mass-audobon",
    category: "landscape",
    location: "Princeton MA",
    altText: "A spider web made visible by morning dew and sunrise in Princeton",
    imageSrc: "/gallery/landscapes/sunrise-wachusett-meadow-mass-audobon.jpg",
    featured: true,
    inGallery: true,
    inStore: true,
  },
  {
    id: "16",
    title: "View from West Bond",
    slug: "view-of-bondcliff-from-west-bond-nh",
    category: "landscape",
    location: "Pemigewasset Wilderness",
    altText: "View of Bondcliff Mountain and the Pemi Loop from West Bond in the White Mountains of New Hampshire",
    imageSrc: "/gallery/landscapes/view-of-bondcliff-from-west-bond-nh.jpg",
    featured: true,
    inGallery: true,
    inStore: false,
  },
  {
    id: "17",
    title: "Stick Season",
    slug: "wild-wasp-nest-ma-dcr",
    category: "wildlife",
    location: "Barre MA",
    altText: "A large wild wasp nest exposed during fall when leaves have dropped",
    imageSrc: "/gallery/wildlife/wild-wasp-nest-ma-dcr.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "18",
    title: "Morning View",
    slug: "winnekeag-sunrise-ashburnham-ma",
    category: "landscape",
    location: "Ashburnham MA",
    altText: "A summer sunrise over a misty Massachusetts lake",
    imageSrc: "/gallery/landscapes/winnekeag-sunrise-ashburnham-ma.jpg",
    featured: false,
    inGallery: true,
    inStore: false,
  },
  {
    id: "19",
    title: "Fall Falls",
    slug: "zealand-falls-wmnf-new-hampshire",
    category: "landscape",
    location: "Zealand Hut",
    altText: "Looking down Zealand Falls near Zealand Falls Hut in the White Mountains of New Hampshire",
    imageSrc: "/gallery/landscapes/zealand-falls-wmnf-new-hampshire.jpg",
    featured: true,
    inGallery: true,
    inStore: false,
  },
  {
    id: "20",
    title: "Franconia Ridge Sunrise",
    slug: "franconia-ridge-sunrise-mt-lafayette-wmnf",
    category: "landscape",
    location: "Franconia Notch NH",
    altText: "Looking south down the Franconia Ridge Loop Trail in the White Mountain National Forest",
    imageSrc: "/gallery/landscapes/franconia-ridge-sunrise-mt-lafayette-wmnf.jpg",
    featured: true,
    inGallery: true,
    inStore: true,
    dateTaken: "7/11/2026",
  }
];

export function getByCategory(category: GalleryCategory): GalleryItem[] {
  return galleryItems.filter((item) => item.category === category);
}

export function getGalleryItems(): GalleryItem[] {
  return galleryItems.filter((item) => item.inGallery);
}

export function getStoreItems(): GalleryItem[] {
  return galleryItems.filter((item) => item.inStore);
}

export function getHomepagePreviews(): {
  gallery: GalleryItem[];
  store: GalleryItem[];
} {
  const usedSlugs = new Set<string>();

  const store = galleryItems
    .filter((item) => item.featured && item.inStore)
    .slice(0, HOMEPAGE_PREVIEW_LIMIT);
  store.forEach((item) => usedSlugs.add(item.slug));

  const gallery = galleryItems
    .filter((item) => item.featured && item.inGallery && !usedSlugs.has(item.slug))
    .slice(0, HOMEPAGE_PREVIEW_LIMIT);

  return { gallery, store };
}

export function getFeaturedGallery(): GalleryItem[] {
  return galleryItems.filter((item) => item.featured && item.inGallery);
}

export function getFeaturedStore(): GalleryItem[] {
  return galleryItems.filter((item) => item.featured && item.inStore);
}

/** @deprecated Use getFeaturedGallery or getFeaturedStore */
export function getFeatured(): GalleryItem[] {
  return galleryItems.filter((item) => item.featured);
}

/** @deprecated Use getStoreItems */
export function getPrints(): GalleryItem[] {
  return getStoreItems();
}

export function getBySlug(slug: string): GalleryItem | undefined {
  return galleryItems.find((item) => item.slug === slug);
}

/** @deprecated Use galleryItems */
export const featuredGallery = galleryItems;
