// @generated by scripts/sync-data.mjs — do not edit by hand
import { galleryItems, type GalleryItem } from "./gallery";

export type PrintOffering = {
  id: string;
  slug: string;
  label: string;
  description: string;
  medium: "print" | "canvas";
  stripeProductId: string;
  active: boolean;
};

export type StoreConfig = {
  stripeShippingProductId: string;
  checkoutEnabled: boolean;
  shipsTo: string;
  turnaroundDays: string;
};

export const printOfferings: PrintOffering[] = [
  {
    id: "prod_UtdLXpdehryKj5",
    slug: "franconia-ridge-sunrise-mt-lafayette-wmnf",
    label: "Franconia Ridge Sunrise - 20x30 Print",
    description: "Fine Art Prints feature a subtle watercolor texture and a smooth matte finish",
    medium: "print",
    stripeProductId: "prod_UtdLXpdehryKj5",
    active: true,
  },
  {
    id: "prod_UtdKMrS5nWCc0n",
    slug: "franconia-ridge-sunrise-mt-lafayette-wmnf",
    label: "Franconia Ridge Sunrise - 12x18 Print",
    description: "Fine Art Prints feature a subtle watercolor texture and a smooth matte finish",
    medium: "print",
    stripeProductId: "prod_UtdKMrS5nWCc0n",
    active: true,
  },
  {
    id: "prod_UtdJuBhkhlX3Hq",
    slug: "franconia-ridge-sunrise-mt-lafayette-wmnf",
    label: "Franconia Ridge Sunrise - 8x12 Print",
    description: "Fine Art Prints feature a subtle watercolor texture and a smooth matte finish",
    medium: "print",
    stripeProductId: "prod_UtdJuBhkhlX3Hq",
    active: true,
  },
  {
    id: "prod_Utd4pRZptJXXzx",
    slug: "franconia-ridge-sunrise-mt-lafayette-wmnf",
    label: "Franconia Ridge Sunrise - 12x18 Canvas",
    description: "Canvas print on certified archival quality canvas wrapped around a 1.5” wood stretcher frame.",
    medium: "canvas",
    stripeProductId: "prod_Utd4pRZptJXXzx",
    active: true,
  },
  {
    id: "prod_UtaASU9VRlJGqP",
    slug: "franconia-ridge-sunrise-mt-lafayette-wmnf",
    label: "Franconia Ridge Sunrise - 20x30 Canvas",
    description: "Canvas print on certified archival quality canvas wrapped around a 1.5” wood stretcher frame.",
    medium: "canvas",
    stripeProductId: "prod_UtaASU9VRlJGqP",
    active: true,
  },
  {
    id: "prod_UtgFQpynA3vJhK",
    slug: "view-of-bondcliff-from-west-bond-nh",
    label: "View of Bondcliff from West Bond - 12x24 Print",
    description: "Fine Art Prints feature a subtle watercolor texture and a smooth matte finish",
    medium: "print",
    stripeProductId: "prod_UtgFQpynA3vJhK",
    active: true,
  },
  {
    id: "prod_UtgGg6AAJ34O1G",
    slug: "view-of-bondcliff-from-west-bond-nh",
    label: "View of Bondcliff from West Bond - 10x20 Print",
    description: "Fine Art Prints feature a subtle watercolor texture and a smooth matte finish",
    medium: "print",
    stripeProductId: "prod_UtgGg6AAJ34O1G",
    active: true,
  },
  {
    id: "prod_UtgHEWcQAxHqwL",
    slug: "view-of-bondcliff-from-west-bond-nh",
    label: "View of Bondcliff from West Bond - 15x30 Canvas",
    description: "Canvas print on certified archival quality canvas wrapped around a 1.5” wood stretcher frame.",
    medium: "canvas",
    stripeProductId: "prod_UtgHEWcQAxHqwL",
    active: true,
  },
  {
    id: "prod_UtgItKGOwk5ZnJ",
    slug: "view-of-bondcliff-from-west-bond-nh",
    label: "View of Bondcliff from West Bond - 10x20 Canvas",
    description: "Canvas print on certified archival quality canvas wrapped around a 1.5” wood stretcher frame.",
    medium: "canvas",
    stripeProductId: "prod_UtgItKGOwk5ZnJ",
    active: true,
  }
];

export const storeConfig: StoreConfig = {
  stripeShippingProductId: "prod_UtdenSZc9pA9Bs",
  checkoutEnabled: true,
  shipsTo: "US",
  turnaroundDays: "7-14",
};

export function getActiveOfferings(): PrintOffering[] {
  return printOfferings.filter((offering) => offering.active);
}

export function getOfferingsForSlug(slug: string): PrintOffering[] {
  const item = galleryItems.find((entry) => entry.slug === slug);
  if (!item || !item.inStore) return [];

  return getActiveOfferings().filter((offering) => offering.slug === slug);
}

export function getStoreItemForSlug(slug: string): GalleryItem | undefined {
  return galleryItems.find((item) => item.slug === slug && item.inStore);
}
